// Falske data med samme form som GET /api/beers, så mockups kan sammenlignes på lige vilkår.
window.BEERS = [
  { name: "Westvleteren 12", breweries: ["Sint-Sixtusabdij"], releaseYear: 2019, drinkingYear: 2024, abv: 10.2, fermentation: "Overgæret", yeastType: "Ale", price: 145, rating: 4.8, untappdRating: 4.47,
    foodPairing: "Lagret gouda, mørk chokolade", description: "Rosin, figen og karamel. Blev bedre af fem år i kælderen, og Jonas nægter stadig at dele sin sidste.",
    hops: ["Northern Brewer", "Styrian Golding"], malts: ["Pilsner", "Mørk kandissukker"], adjuncts: ["Kandissukker"], types: ["Quadrupel", "Trappist"] },
  { name: "Oude Geuze", breweries: ["Brouwerij 3 Fonteinen"], releaseYear: 2021, drinkingYear: 2024, abv: 6.0, fermentation: "Spontan", yeastType: "Vild", price: 110, rating: 4.4, untappdRating: 4.12,
    foodPairing: "Østers, moules frites", description: "Stald, citron og tør som et gammelt bibliotek. Delte meninger om staldduften.",
    hops: ["Lagrede humler"], malts: ["Pilsner", "Umaltet hvede"], adjuncts: [], types: ["Gueuze", "Lambic"] },
  { name: "Mørk Mosaik", breweries: ["Amager Bryghus"], releaseYear: 2023, drinkingYear: 2023, abv: 7.4, fermentation: "Overgæret", yeastType: "Ale", price: 42, rating: 3.6, untappdRating: 3.81,
    foodPairing: "Burger", description: "Sort IPA der ikke helt kunne bestemme sig. Mosaic dominerer, ristningen forsvinder.",
    hops: ["Mosaic", "Citra"], malts: ["Pale Ale", "Carafa III"], adjuncts: [], types: ["Black IPA"] },
  { name: "Sur Sommer", breweries: ["To Øl", "Mikkeller"], releaseYear: 2024, drinkingYear: 2024, abv: 4.5, fermentation: "Blandet", yeastType: "Brett", price: 38, rating: 3.9, untappdRating: 3.64,
    foodPairing: "Ceviche", description: "Hindbær og rabarber, syrlig men ikke skarp. Forsvandt hurtigt i solen.",
    hops: ["Saaz"], malts: ["Pilsner", "Hvede"], adjuncts: ["Hindbær", "Rabarber"], types: ["Sour", "Frugtøl"] },
  { name: "Kellerbier", breweries: ["Brauerei Mahr's"], releaseYear: 2024, drinkingYear: 2024, abv: 4.9, fermentation: "Undergæret", yeastType: "Lager", price: 29, rating: 4.1, untappdRating: 3.72,
    foodPairing: "Pølser, kringle", description: "Ufiltreret, brød og blomster. Det bedste argument for at drikke lager.",
    hops: ["Hallertauer Mittelfrüh"], malts: ["Pilsner", "Wiener"], adjuncts: [], types: ["Kellerbier", "Lager"] },
  { name: "Imperial Vanilla Hygge", breweries: ["Evil Twin"], releaseYear: 2020, drinkingYear: 2023, abv: 12.0, fermentation: "Overgæret", yeastType: "Ale", price: 89, rating: 3.2, untappdRating: 4.05,
    foodPairing: "Vaniljeis", description: "Som at drikke en kage. Untappd elsker den, Røverne blev mætte efter to slurke.",
    hops: ["Magnum"], malts: ["Maris Otter", "Chokolademalt", "Havre"], adjuncts: ["Vanilje", "Laktose", "Kakao"], types: ["Imperial Stout", "Pastry"] },
  { name: "Saison Dupont", breweries: ["Brasserie Dupont"], releaseYear: 2023, drinkingYear: 2024, abv: 6.5, fermentation: "Overgæret", yeastType: "Saison", price: 34, rating: 4.3, untappdRating: 3.95,
    foodPairing: "Grillet kylling, gedeost", description: "Peber, citronskal og masser af bobler. Referencen for stilen.",
    hops: ["East Kent Golding", "Styrian Golding"], malts: ["Pilsner"], adjuncts: [], types: ["Saison", "Farmhouse"] },
  { name: "Humlefryd", breweries: ["Dry & Bitter"], releaseYear: 2024, drinkingYear: 2024, abv: 6.8, fermentation: "Overgæret", yeastType: "Ale", price: 48, rating: 4.0, untappdRating: 3.98,
    foodPairing: "Thai-karry", description: "Uklar NEIPA med mango og fersken. Friskhed er alt, den blev drukket tre uger efter tapning.",
    hops: ["Citra", "Galaxy", "Nelson Sauvin"], malts: ["Pilsner", "Havre", "Hvede"], adjuncts: [], types: ["NEIPA", "IPA"] },
  { name: "Rauchbier Märzen", breweries: ["Schlenkerla"], releaseYear: 2023, drinkingYear: 2023, abv: 5.1, fermentation: "Undergæret", yeastType: "Lager", price: 32, rating: 2.9, untappdRating: 3.78,
    foodPairing: "Røget skinke", description: "Flydende bacon. Én Røver elskede den, resten gik efter vand.",
    hops: ["Hallertauer"], malts: ["Bøgerøget malt"], adjuncts: [], types: ["Rauchbier", "Märzen"] },
  { name: "Kriek Boon", breweries: ["Brouwerij Boon"], releaseYear: 2022, drinkingYear: 2024, abv: 4.0, fermentation: "Spontan", yeastType: "Vild", price: 40, rating: 3.7, untappdRating: 3.66,
    foodPairing: "Andebryst", description: "Kirsebær og mandel, blødere end ventet.",
    hops: ["Lagrede humler"], malts: ["Pilsner", "Umaltet hvede"], adjuncts: ["Kirsebær"], types: ["Kriek", "Lambic"] }
];
